### ISSUE TITLE
Do not set values on profile startup

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-SST/profile_collection#4]
While attempting to start the collection profile with IPython (=`bsui`) from xf07id1-ca1, I noticed that the following values are set during loading of the profile: https://github.com/NSLS-II-SST/profile_collection/blob/cb4b7cb3a17ce15c7d9a7b5ccdadf5be55760af1/startup/12-slits.py#L61-L72

That can be dangerous if someone starts another IPython session with these startup files, which may reset the values for the running experiment. Better to wrap it to a plan in which the things can be set via `yield from bps.mv(...)`, and then actually set as a part of RE run.

**Comment by EliotGann** [comment]
hmm ... I'm not sure.  I would like to make sure these are set during the startup.  These offsets will not be reset during any normal operations, so setting them again is not too bad...  I could put it in an init method?  it would still be called though.

**Comment by EliotGann** [comment]
Changed it to a function
