### ISSUE TITLE
EPICS vars configuration on Linux

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-SST/profile_collection#6]
We configured the `EPICS_CA_*` vars on Windows to make it work with caproto + various IOCs on the floor. It would be nice to have that configuration documented here, so that it can be propagated to the future machines for RSoXS.

@EliotGann, do you mind to provide the configuration stored on xf07id1-ws18?

**Comment by EliotGann** [comment]
EPICS_CA_AUTO_ADDR_LIST is set to yes, that is the only variable we had to set.  We did have to change how caproto does it's auto finding though, because there were two NICs

**Comment by mrakitin** [comment]
Thanks!
